### ISSUE TITLE
Add canopy source STEP files

### ISSUE THREAD

**Issue by robhaswell** [OpenRacer/OpenRacer#14]
OpenRacer provides STL files for its canopies and lockers, but this is not an "open" format and is akin to shipping compiled binaries. The STL files can be used but editing them is problematic at best, as they have been compiled down to triangles and details such as the fillets, projections, etc have been lost.

It would be great if the source CAD files could be uploaded in an editable format, e.g. STEP or the native format of a widely accessible CAD software like Fusion. The canopies are a large part of the overall frame and allowing users to edit them can only bring benefits to the project.

**Comment by limonspb** [comment]
there are lotsand lots of files/canopies. So im just giving them on demand in whatever format you like.
What canopy are you interested in?

**Comment by robhaswell** [comment]
That would be great - thanks. I'm mainly interested in making an Nano90 Classic, so whatever is close to that, I would also like to make some small modifications to the Nano90 Pro. I also want to make one for Walksnail so probably the Vista pod is closest to that.

One of the camera lockers would be good as well, I can probably modify just one.

Please could you send them in something I can load into Fusion 360, maybe STEP, or any other free CAD software so I can open them up. Thanks!

**Comment by limonspb** [comment]
Sorry, a few days late.
this is PRO Hdzero nano 90:
https://drive.google.com/file/d/1pW9J78KofWkMK_4MHuWfZwMmcR0p2MqG/view?usp=share_link

uploading others...
its fusion 360 format.
The problem with STEP - its not easy to modify... the problem with fusion 360 format - its really long process to export for whatever reason... They removed the ability to share a link from the free versions :/

**Comment by limonspb** [comment]
Classic HDZero Runcam Nano canopy (fusion 360 format)
https://drive.google.com/file/d/1Ni-tkZ5jCdnCcezemONlrfmZabkeVe8s/view?usp=share_link

**Comment by limonspb** [comment]
DJI O3 canopy - could be the closes to walksnail:
https://drive.google.com/file/d/1RYrezc8Wb_teqbTwLZSnPBn9lSPifbR1/view?usp=share_link

**Comment by limonspb** [comment]
@robhaswell make sure that before importing you create a separate folder in Fusion 360, because importing these files creates a bunch of little subfiles with all separate components...

**Comment by robhaswell** [comment]
Awesome, thanks @limonspb
